---
- import_playbook: check_cisco_ios_bgp_as.yaml

- hosts: routers
  vars:
  - asnum: 65000
  tasks:
  - assert: # For whatever reason this is evaluated as a FALSE not TRUE -> this playbook is not working correctly. Update - it works with bgp_as|int
      that: |
        bgp_as is not defined or
        bgp_as|int == asnum 
      success_msg: ASNUM IS 65000
      msg:  Wrong BGP AS number {{ bgp_as|default('') }} configured on the box

  - name: "Configure BGP neighbor on Cisco IOS"
    ios_config:
      parents:
        - "router bgp {{ bgp_as }}"
      lines:
        - "neighbor 172.16.1.102 remote-as 65002"