---
- name: "PLAYBOOK 1: SETUP DIRECTORY on the local host"
  hosts: localhost
  tasks:
    - name: "TASK 1: Setup environment - remove directory if it exist"
      ansible.builtin.file:
        path: results
        state: absent
    - name: "TASK 2: Create new directory"
      ansible.builtin.file:
        path: results
        state: directory

- name: "PLAYBOOK 2: Collect printouts from networking devices"
  hosts: routers
  tasks:
    - name: "TASK 1: Execute show command"
      cisco.ios.ios_command:
        commands:
          - "show arp"
      register: result
    
    - name: "TASK 2: COPY PRINTOUT TO RESULT DIRECTORY"
      ansible.builtin.copy:
        content: "{{ result.stdout[0] }}"
        dest: "results/{{ inventory_hostname }}_show_arp.txt"
      delegate_to: localhost


