---
- name: PLAYBOOK - CONGIGURE LAYER3 INTERFACES
  hosts: routers
  tasks:
    - name: TASK - IMPORT YAML DATA FOR ROUTERS
      ansible.builtin.set_fact:
       interface_data: "{{ lookup('file', 'interfaces_data.yaml') | from_yaml }}"
    - name: TASK - CONFIGURE LAYER3 interfaces on ROUTERS
      cisco.ios.ios_config:
        lines:
          - "ip address {{ item.ip }} 255.255.255.0" 
          - "description {{ item.description }}"
        parents: "interface {{ item.interface }}"
      with_items: "{{ interface_data['%s' | format(inventory_hostname)] }}"